#!/usr/bin/env node
// Build worker/src/blog_posts.ts from Gemini-daemon markdown drafts.
//
// Reads:   ~/Documents/writer/daemon/output/2026-*/substack-*.md
// Writes:  worker/src/blog_posts.ts
//
// Each post:
//   - Parses bold-text frontmatter (**Subtitle:**, **Slug:**, **Date:**)
//   - Title from first `# H1`
//   - Strips "Pre-Publish Checklist & SERP Geometry" tail (editorial meta)
//   - Body markdown → HTML via `marked`
//   - Synthesizes a ~155-char description from the first ¶ for og:description
//
// Re-run after the Gemini daemon emits new drafts: `node scripts/build_blog_posts.mjs`

import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { marked } from "marked";

const ROOT = join(homedir(), "Documents/writer/daemon/output");
const OUT  = join(import.meta.dirname, "..", "src", "blog_posts.ts");

function listDrafts() {
  const drafts = [];
  for (const run of readdirSync(ROOT)) {
    if (run.startsWith("_") || run === "scratch") continue;
    const runDir = join(ROOT, run);
    if (!statSync(runDir).isDirectory()) continue;
    for (const f of readdirSync(runDir)) {
      if (!/^substack-\d+\.md$/.test(f)) continue;
      drafts.push({ run, path: join(runDir, f) });
    }
  }
  return drafts;
}

function parseFrontmatter(md) {
  // Bold-text frontmatter sits in the first ~20 lines.
  const lines = md.split(/\r?\n/);
  const meta = {};
  for (const line of lines.slice(0, 30)) {
    const m = line.match(/^\*\*(Subtitle|Slug|Author|Date|Primary Search Query|Target Word Count):\*\*\s*(.+)$/i);
    if (m) meta[m[1].toLowerCase().replace(/\s+/g, "_")] = m[2].trim();
  }
  return meta;
}

function extractTitle(md) {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : "Untitled";
}

function stripEditorialTail(md) {
  // Cut everything from "Pre-Publish Checklist", "Audit Trail", or
  // "SERP Geometry" onward — those are daemon meta sections.
  const cut = md.search(/\n-{2,}\s*\n\s*##?\s+(Pre-?Publish Checklist|SERP Geometry|Audit Trail|Pre-publish checklist)/i);
  if (cut > 0) return md.slice(0, cut);
  return md;
}

function stripFrontmatter(md) {
  // Drop the title line + bold-text frontmatter so the body starts at the
  // first ## subhead. We re-render the title separately in the page template.
  const lines = md.split(/\r?\n/);
  // Find the first `---` separator after frontmatter
  for (let i = 0; i < lines.length; i++) {
    if (/^---+$/.test(lines[i])) {
      return lines.slice(i + 1).join("\n").replace(/^\s+/, "");
    }
  }
  // Fallback: strip until first ## subhead
  const subIdx = lines.findIndex((l) => /^##\s/.test(l));
  return subIdx > 0 ? lines.slice(subIdx).join("\n") : md;
}

function synthDescription(md) {
  // First paragraph of body, sans markdown, ~155 chars for og:description.
  const lines = stripFrontmatter(md).split(/\r?\n/);
  for (const l of lines) {
    const t = l.trim();
    if (!t || /^#/.test(t) || /^>/.test(t) || /^\*\*Slug/.test(t)) continue;
    const plain = t
      .replace(/`([^`]+)`/g, "$1")
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
    if (plain.length < 40) continue;
    return plain.length > 155 ? plain.slice(0, 152).trimEnd() + "…" : plain;
  }
  return "wmcp.sh engineering notes.";
}

// --- main ---

const drafts = listDrafts();
console.log(`Found ${drafts.length} substack drafts`);

const seen = new Set();
const posts = [];

for (const { run, path } of drafts) {
  const md = readFileSync(path, "utf8");
  const meta = parseFrontmatter(md);
  if (!meta.slug) {
    console.warn(`  skip (no slug): ${path}`);
    continue;
  }
  const slug = meta.slug.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "");
  if (seen.has(slug)) { continue; } // de-dupe across runs
  seen.add(slug);

  const title = extractTitle(md);
  const body = stripEditorialTail(stripFrontmatter(md));
  const html = marked.parse(body, { breaks: false, gfm: true });
  const description = synthDescription(md);

  posts.push({
    slug,
    title,
    subtitle: meta.subtitle || "",
    date: meta.date || "2026-05-28",
    primary_query: meta.primary_search_query || "",
    description,
    html: html.trim(),
    source_run: run,
  });
}

// Sort newest first by date desc, then slug asc.
posts.sort((a, b) => (b.date.localeCompare(a.date)) || a.slug.localeCompare(b.slug));

console.log(`Emitting ${posts.length} unique posts → ${OUT}`);

const header = `// AUTO-GENERATED by scripts/build_blog_posts.mjs — DO NOT EDIT BY HAND.
// Source: ~/Documents/writer/daemon/output/2026-*/substack-*.md
// Re-run: \`node worker/scripts/build_blog_posts.mjs\` after the daemon emits new drafts.

export interface BlogPost {
  slug: string;
  title: string;
  subtitle: string;
  date: string;
  description: string;
  primary_query: string;
  html: string;
  source_run: string;
}

export const BLOG_POSTS: Record<string, BlogPost> = `;

writeFileSync(OUT, header + JSON.stringify(Object.fromEntries(posts.map(p => [p.slug, p])), null, 2) + ";\n\nexport const BLOG_SLUGS: string[] = " + JSON.stringify(posts.map(p => p.slug)) + ";\n");

console.log("done");
