#!/bin/bash
# build_kit.sh — produce the full launch video set from the 4 source clips.
#
# Inputs (from out/):
#   wmcp-agent.mp4, wmcp-claude-code.mp4, wmcp-codex.mp4, wmcp-grok.mp4
#   _overlay-watermark.png, _overlay-title.png, _overlay-end.png
#     (generated by gen_overlays.py)
#
# Outputs (into out/):
#   wmcp-<clip>-wm.mp4   — each clip with the wmcp.sh badge, normalized 1280×720
#   wmcp-hero.mp4        — full supercut: title + 4 clips + end

set -euo pipefail
cd "$(dirname "$0")"

OUT="out"

# Make sure the overlay PNGs exist
[ -f "$OUT/_overlay-watermark.png" ] || python3 gen_overlays.py

# Common normalize-to-1280×720 step (letterbox with the brand bg color)
NORMALIZE="scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=#07070d,setsar=1"

CLIPS=(agent claude-code codex grok)

# ─────────────────────────────────────────────────────────────────────
# Step 1 — watermark + normalize each clip
# ─────────────────────────────────────────────────────────────────────
echo "==== watermarking + normalizing 4 clips ===="
for c in "${CLIPS[@]}"; do
  in="$OUT/wmcp-${c}.mp4"
  out="$OUT/wmcp-${c}-wm.mp4"
  [ -f "$in" ] || { echo "× missing $in"; exit 1; }
  # Overlay the watermark PNG at bottom-right (28px margin)
  ffmpeg -y -i "$in" -i "$OUT/_overlay-watermark.png" \
    -filter_complex "[0:v]${NORMALIZE}[v0];[v0][1:v]overlay=W-w-28:H-h-22" \
    -r 30 \
    -c:v libx264 -preset slow -crf 22 -pix_fmt yuv420p -movflags +faststart \
    -an \
    "$out" 2>&1 | tail -1
  echo "  ✓ $out"
done

# ─────────────────────────────────────────────────────────────────────
# Step 2 — title (3s) + end (4s) clips from the PNG cards
# ─────────────────────────────────────────────────────────────────────
echo ""
echo "==== building title + end clips ===="

ffmpeg -y -loop 1 -i "$OUT/_overlay-title.png" \
  -t 3 -r 30 \
  -c:v libx264 -preset slow -crf 22 -pix_fmt yuv420p -movflags +faststart \
  -an \
  "$OUT/_title.mp4" 2>&1 | tail -1
echo "  ✓ _title.mp4"

ffmpeg -y -loop 1 -i "$OUT/_overlay-end.png" \
  -t 4 -r 30 \
  -c:v libx264 -preset slow -crf 22 -pix_fmt yuv420p -movflags +faststart \
  -an \
  "$OUT/_end.mp4" 2>&1 | tail -1
echo "  ✓ _end.mp4"

# ─────────────────────────────────────────────────────────────────────
# Step 3 — concat into supercut
# ─────────────────────────────────────────────────────────────────────
echo ""
echo "==== concatenating supercut ===="

cat > "$OUT/_concat.txt" <<EOF
file '_title.mp4'
file 'wmcp-agent-wm.mp4'
file 'wmcp-claude-code-wm.mp4'
file 'wmcp-codex-wm.mp4'
file 'wmcp-grok-wm.mp4'
file '_end.mp4'
EOF

ffmpeg -y -f concat -safe 0 -i "$OUT/_concat.txt" \
  -c copy -movflags +faststart \
  "$OUT/wmcp-hero.mp4" 2>&1 | tail -1

# Cleanup intermediate files
rm "$OUT/_concat.txt" "$OUT/_title.mp4" "$OUT/_end.mp4"

# ─────────────────────────────────────────────────────────────────────
echo ""
echo "==== launch kit ===="
for f in "$OUT"/wmcp-*-wm.mp4 "$OUT"/wmcp-hero.mp4; do
  [ -f "$f" ] || continue
  d=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$f" | python3 -c "import sys; print(round(float(sys.stdin.read()),1))")
  sz=$(stat -f%z "$f")
  echo "  $f  ${d}s  $((sz/1024))KB"
done
